version: '3.3'

services:
  filebeat:
    container_name: filebeat
    build:
      context: /home/ubuntu/Express
      dockerfile: ./Dockerfile.filebeat
    volumes:
      - shared-log:/var/log/server

  express:
    container_name: express
    build:
      context: /home/ubuntu/Express
      dockerfile: ./Dockerfile.express
    volumes:
      - /server/node_modules
      - /home/ubuntu/Express:/server
      - shared-log:/server/log
    ports:
      - '3000:3000'
    command: ['npm', 'run', 'dev']
    networks:
      - inner-network

networks:
  inner-network:
    driver: bridge

volumes:
  shared-log:
