version: '3.3'

services:
  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.1.0
    volumes:
      - /home/ubuntu/project:/server
      - /home/ubuntu/project/deploy/dev/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - /home/ubuntu/project/log:/server/log

  express:
    container_name: express
    build:
      context: /home/ubuntu/project
      dockerfile: ./Dockerfile.express
    volumes:
      - /server/node_modules
    ports:
      - '3000:3000'
    command: ['npm', 'run', 'dev']
    networks:
      - inner-network

networks:
  inner-network:
    driver: bridge
