version: '3.3'

services:
  filebeat:
    container_name: filebeat
    image: docker.elastic.co/beats/filebeat:7.10.2
    user: ubuntu
    volumes:
      - /home/ubuntu/project/deploy/dev/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - fbdata:/usr/share/filebeat/logs/
      - /home/ubuntu/project/log/:/usr/share/filebeat/logs/

  express:
    container_name: express
    build:
      context: /home/ubuntu/project
      dockerfile: ./Dockerfile.express
    volumes:
      - /server/node_modules
    ports:
      - '3000:3000'
    command: ['npm', 'run', 'dev']
    networks:
      - inner-network

networks:
  inner-network:
    driver: bridge

volumes:
  fbdata:
    driver: local
