# input
filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - '/var/log/server/*.log'

# output
output.elasticsearch:
  hosts: ['']
  protocol: 'https'
  username: ''
  password: ''

setup.ilm.enabled: false
setup.pack.security.enabled: false
setup.xpack.graph.enabled: false
setup.xpack.watcher.enabled: false
setup.xpack.monitoring.enabled: false
setup.xpack.reporting.enabled: false
setup.template.overwrite: true
setup.template.enabled: true
