version: '3.3'

services:
  elasticsearch01:
    container_name: elasticsearch01
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.10.2
    volumes:
      - ./elasticsearch/config/elasticsearch01.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /etc/localtime:/etc/localtime:ro
      - es01:/usr/share/elasticsearch/data
    ulimits:
      memlock: # 메모리 내 주소 공간의 최대 크기
        soft: -1 # 프로그램 시작 시 적용하는 기본 한도, unlimited
        hard: -1 # 프로그램 시작 시 적용하는 최대 한도, unlimited
    ports:
      - '9200:9200' # http port(9200-9299)
      - '9300:9300' # tcp포트(9300-9399)
    environment:
      ES_JAVA_OPTS: '-Xms512m -Xmx512m' # -Xms: minimum heap size, -Xmx: maximum heap size
    networks:
      - es-network

  elasticsearch02:
    container_name: elasticsearch02
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.10.2
    volumes:
      - ./elasticsearch/config/elasticsearch02.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /etc/localtime:/etc/localtime:ro
      - es02:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9301:9300' # 9300:9300일 경우 외부 연결포트가 master-node와 중복
    environment:
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      discovery.zen.ping.unicast.hosts: 'elasticsearch01'
    networks:
      - es-network
    depends_on:
      - elasticsearch01

  elasticsearch03:
    container_name: elasticsearch03
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: 7.10.2
    volumes:
      - ./elasticsearch/config/elasticsearch03.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      - /etc/localtime:/etc/localtime:ro
      - es03:/usr/share/elasticsearch/data
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - '9302:9300' # 9300:9300일 경우 외부 연결포트가 master-node와 중복
    environment:
      ES_JAVA_OPTS: '-Xms512m -Xmx512m'
      discovery.zen.ping.unicast.hosts: 'elasticsearch01'
    networks:
      - es-network
    depends_on:
      - elasticsearch01

  logstash:
    container_name: logstash
    build:
      context: logstash/
      args:
        ELK_VERSION: 7.10.2
    volumes:
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '5044:5044'
      - '9600:9600'
    environment:
      LS_JAVA_OPTS: '-Xmx1G -Xms1G'
    networks:
      - es-network
    depends_on:
      - elasticsearch01

  kibana:
    container_name: kibana
    build:
      context: kibana/
      args:
        ELK_VERSION: 7.10.2
    volumes:
      - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - '5601:5601'
    networks:
      - es-network
    depends_on:
      - elasticsearch01

networks:
  es-network:
    driver: bridge

volumes:
  es01:
    driver: local
  es02:
    driver: local
  es03:
    driver: local
